name: Deploy Backend to Azure App Service

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Zip artifact
        working-directory: backend
        run: zip -r ../api.zip . -x "*/__pycache__/*" ".venv/*"

      - name: Zip artifact
        run: |
          cd backend
          zip -r ../api.zip . -x "*/__pycache__/*" "*/.venv/*"

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: Night-Crawler-Backend
          package: api.zip
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_BACKEND }}
