name: Deploy Frontend to Azure App Service

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install
        working-directory: frontend
        run: npm ci

      - name: Build (inject VITE_API_URL)
        working-directory: frontend
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL_PROD }}
        run: npm run build

      - name: Zip dist -> web.zip (root)
        working-directory: frontend/dist
        run: zip -r ../../web.zip .

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: Night-Crawler-Frontend
          package: web.zip
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_FRONTEND }}
